apiVersion: apps/v1
kind: Deployment
metadata:
  name: {resource_name}
  namespace: {namespace}
  labels:
    app: {resource_name}
spec:
  selector:
    matchLabels:
      app: {resource_name}
  template:
    metadata:
      labels:
        app: {resource_name}
    spec:
      containers:
      - name: {resource_name}
        image: {image_name}
        ports:
        - containerPort: 8080
          name: http
